f=open("hello.txt")
# t_lines=f.readlines()
# print(t_lines,type(t_lines))
# line1=f.readline()
# line2=f.readline()
# print(line1,line2,type(line1))
# f.close()
# line5=f.readline()
# print(line5,type(line5))
line=f.readline()
while(line!=""):
    print(line)
    line=f.readline()
f.close()