n=int(input("Enter the number"))
n1=int(input("Enter the number"))
print(f"The numbers are {n} and {n1}")
print(f"Addition :{n+n1}")
print(f"Subtraction :{n-n1}")
print(f"Multiplication :{n*n1}")
print(f"Divison :{n/n1}")
print(f"Floor Divison :{n//n1}")
print(f"The power of {n} is :",n**2)
print(f"The power of {n1} is :",n1**2)